# Generated by Django 6.0.3 on 2026-03-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_game_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='playable_on',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
