# Generated by Django 6.0.3 on 2026-03-31 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_platform_platform_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='highlight_image_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
