# Generated by Django 6.0.3 on 2026-04-20 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_platform_highlight_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='console',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
