# Generated by Django 6.0.3 on 2026-06-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_devices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('img_url', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Devices',
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ManyToManyField(related_name='devices', to='store.devicetype'),
        ),
    ]
