# Generated by Django 6.0.3 on 2026-06-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_cartitem_device_item_alter_cartitem_game_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='type',
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='check_single_item_type',
        ),
        migrations.DeleteModel(
            name='DeviceType',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='device_item',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
