# Generated by Django 6.0.3 on 2026-03-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_game_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='quantity_sold',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
