# Generated by Django 6.0.3 on 2026-03-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_console'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='consoles',
            field=models.ManyToManyField(related_name='games', to='store.console'),
        ),
    ]
