# Generated by Django 6.0.3 on 2026-03-29 01:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_game_consoles'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='platform_icon',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
