# Generated by Django 6.0.3 on 2026-06-22 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_device_devicetype_delete_devices_device_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='type',
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.devicetype'),
            preserve_default=False,
        ),
    ]
