# Generated by Django 6.0.3 on 2026-06-22 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_device_type_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='device_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.device'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='game_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.game'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('device_item__isnull', True), ('game_item__isnull', False)), models.Q(('device_item__isnull', False), ('game_item__isnull', True)), _connector='OR'), name='check_single_item_type'),
        ),
    ]
